import { useRouter } from 'next/router';
import { useQuery } from 'react-query';
import PhotoDetails from '@/components/Details';
import Head from 'next/head';

const BASE_URL = process.env.BASE_URL;
const QUERY_KEY = process.env.QUERY_KEY;

    const getPhotos = async (id: string) => {
        const response = await fetch(`${BASE_URL}/${id}/?${QUERY_KEY}`);
        console.log(response);
        const data = await response.json();
        return data;
    };

function EachPhotoDetail() {

    const router = useRouter();
    const { id } = router.query;
    const { data, isLoading, isError } = useQuery(['photoDetails', id], () => getPhotos(String(id)));

    if (isLoading) {
        return (
            <div className='min-h-screen bg-gray-800 flex justify-center items-center'>
                <p className='text-white text-4xl font-semibold'>Loading...</p>
            </div>
        );
    }

    if (isError) {
        <div className='min-h-screen bg-gray-800 flex justify-center items-center'>
            <p className='text-white text-4xl font-semibold'>Error</p>
        </div>
    }

    return (
        <>

            <Head>
                <title>{id}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <body className='bg-gradient-to-r from-sky-500 to-indigo-500'>
                <main>
                    <div className='p-10'>
                        <PhotoDetails 
                            src={data.urls.regular} 
                            alt={data.alt_description} 
                            desc={data.description} 
                            user={data.user.username} 
                            model={data.exif.model} 
                            camera={data.exif.make} 
                            location={data.location.name} />
                    </div>
                </main>
            </body>


        </>

    );

}

export default EachPhotoDetail;